model: mistralai/Mistral-7B-v0.1
instruction_tuned: false
persona: true
n_style_examples: 10
retrieve_context: true
finetuned: true
ft_variant: ft_lorank
lora_r: 4
lora_alpha: 8
lora_dropout: 0.1
ft_learning_rate: 0.0001
